### ISSUE TITLE
[MAD] More Conveyors - Seems to cause crashes with new update

### ISSUE THREAD

**Issue by LordTylus** [mafoo/Space-Engineers-Mods#1]
Hi, your new Update of More Conveyors looks pretty nice: However we do have a problem with it. A short while after our server updated the mod it started to crash with Conveyor Related Error messages.

Not sure if its actually related to the mod. Or the just the game not liking something about the mod. But we do get the following error Message now.

I thought I would let you know, that crash the server immediately and may even cause som crash loops depending on when it last saved.

Not sure if you can actually do something about it. But maybe you have an idea

Error from Single Player
```
2020-12-03 19:52:34.367 - Thread:   1 ->  Exception occurred: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Sandbox.Game.GameSystems.Conveyors.MyConveyorLine.SplitSections(List`1 sections, Int32 lengthLimit, Vector3I startPosition, Vector3I splittingPosition, List`1 sections1, List`1 sections2, ConveyorLinePosition& newPosition1, ConveyorLinePosition& newPosition2, Int32& line1Length)
   at Sandbox.Game.GameSystems.Conveyors.MyConveyorLine.RemovePortion(Vector3I startPosition, Vector3I endPosition)
   at Sandbox.Game.GameSystems.MyGridConveyorSystem.RemoveSegmentBlock(IMyConveyorSegmentBlock segmentBlock)
   at Sandbox.Game.Entities.Cube.MyCubeGridSystems.UnregisterFromSystems(MyCubeBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveBlockInternal(MySlimBlock block, Boolean close, Boolean markDirtyDisconnects)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveDestroyedBlockInternal(MySlimBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveDestroyedBlock(MySlimBlock block, Int64 attackerId)
   at Sandbox.Game.Entities.Cube.MySlimBlock.ApplyAccumulatedDamage(Boolean addDirtyParts, Int64 attackerId)
   at Sandbox.Game.Entities.Cube.MySlimBlock.DoDamageInternal(Single damage, MyStringHash damageType, Boolean addDirtyParts, Nullable`1 hitInfo, Int64 attackerId)
   at Sandbox.Game.Entities.Cube.MySlimBlock.DoDamage(Single damage, MyStringHash damageType, Nullable`1 hitInfo, Boolean addDirtyParts, Int64 attackerId)
   at Sandbox.Game.Entities.Cube.MySlimBlock.DoDamage(Single damage, MyStringHash damageType, Boolean sync, Nullable`1 hitInfo, Int64 attackerId)
   at Sandbox.Game.Entities.MyCubeGrid.ApplyDestructionDeformationInternal(MySlimBlock block, Boolean sync, Single damage, Int64 attackerId, Boolean postponed)
   at Sandbox.Game.Entities.MyCubeGrid.ApplyDestructionDeformation(MySlimBlock block, Single damage, Nullable`1 hitInfo, Int64 attackerId)
   at Sandbox.Game.MyExplosion.ApplyVolumetricDamageToGrid(MyGridExplosion damageInfo, Int64 attackerId)
   at Sandbox.Game.MyExplosion.ApplyVolumetricDamageToGrid()
   at Sandbox.Game.MyExplosions.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
```

By this it seems to be related to removing a block due to damage. I saw a similar message also:

Error from Torch Server
```
22:14:41.3851 [FATAL]  Initializer: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Sandbox.Game.GameSystems.Conveyors.MyConveyorLine.SplitSections(List`1 sections, Int32 lengthLimit, Vector3I startPosition, Vector3I splittingPosition, List`1 sections1, List`1 sections2, ConveyorLinePosition& newPosition1, ConveyorLinePosition& newPosition2, Int32& line1Length)
   at Sandbox.Game.GameSystems.Conveyors.MyConveyorLine.RemovePortion(Vector3I startPosition, Vector3I endPosition)
   at Sandbox.Game.GameSystems.MyGridConveyorSystem.RemoveSegmentBlock(IMyConveyorSegmentBlock segmentBlock)
   at Sandbox.Game.Entities.Cube.MyCubeGridSystems.UnregisterFromSystems(MyCubeBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveBlockInternal(MySlimBlock block, Boolean close, Boolean markDirtyDisconnects)
   at Patched_Sandbox.Game.Entities.MyCubeGridMoveBlocks_0(MyCubeGrid to, MyCubeGrid cubeBlocks, List`1 offset, Int32 count, Int32 )
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplitForGroup(MyCubeGrid originalGrid, List`1 splitBlocks, Group& group)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplits(MyCubeGrid originalGrid, List`1 splitBlocks, List`1 groups, MyTestDisconnectsReason reason, Boolean sync)
   at Sandbox.Game.Entities.Cube.MyDisconnectHelper.DoDisconnects(MyCubeGrid grid, MyTestDisconnectsReason reason)
   at Sandbox.Game.Entities.MyCubeGrid.Dispatch(UpdateQueue queue, Boolean parallel)
   at Sandbox.Game.Entities.MyCubeGrid.UpdateAfterSimulation()
   at Patched_Sandbox.Game.Entities.MyParallelEntityUpdateOrchestratorUpdateAfterSimulation_0(Object )
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 255
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 120
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Sandbox.Game.GameSystems.Conveyors.MyConveyorLine.SplitSections(List`1 sections, Int32 lengthLimit, Vector3I startPosition, Vector3I splittingPosition, List`1 sections1, List`1 sections2, ConveyorLinePosition& newPosition1, ConveyorLinePosition& newPosition2, Int32& line1Length)
   at Sandbox.Game.GameSystems.Conveyors.MyConveyorLine.RemovePortion(Vector3I startPosition, Vector3I endPosition)
   at Sandbox.Game.GameSystems.MyGridConveyorSystem.RemoveSegmentBlock(IMyConveyorSegmentBlock segmentBlock)
   at Sandbox.Game.Entities.Cube.MyCubeGridSystems.UnregisterFromSystems(MyCubeBlock block)
   at Sandbox.Game.Entities.MyCubeGrid.RemoveBlockInternal(MySlimBlock block, Boolean close, Boolean markDirtyDisconnects)
   at Patched_Sandbox.Game.Entities.MyCubeGridMoveBlocks_0(MyCubeGrid to, MyCubeGrid cubeBlocks, List`1 offset, Int32 count, Int32 )
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplitForGroup(MyCubeGrid originalGrid, List`1 splitBlocks, Group& group)
   at Sandbox.Game.Entities.MyCubeGrid.CreateSplits(MyCubeGrid originalGrid, List`1 splitBlocks, List`1 groups, MyTestDisconnectsReason reason, Boolean sync)
   at Sandbox.Game.Entities.Cube.MyDisconnectHelper.DoDisconnects(MyCubeGrid grid, MyTestDisconnectsReason reason)
   at Sandbox.Game.Entities.MyCubeGrid.Dispatch(UpdateQueue queue, Boolean parallel)
   at Sandbox.Game.Entities.MyCubeGrid.UpdateAfterSimulation()
   at Patched_Sandbox.Game.Entities.MyParallelEntityUpdateOrchestratorUpdateAfterSimulation_0(Object )
   at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchAfterSimulation()
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Patched_Sandbox.Game.World.MySessionUpdateComponents_0(Object )
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 255
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 120
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by LordTylus** [comment]
Unfortunately I cannot see on the Server which version of the mod I had installed at the time it first occured:

By the timestamps the first time it Happened I had the version installed on
Update: 2. Dec at 18:39 (central european time) installed
It continued to crash even after updating to
Update: 3. Dec at 0:17 (central european time) also

Eventually it stopped crashing for a while, probably because the player whose grid is affected did not go there and torch concealment plugin did pause the grid.

However upon returning there it immediately crashed again.

Furthermore I checked the logs and found the following Messages also

```
04:14:02.5833 [DEBUG]  Keen:       MOD_ERROR: [MAD] More Conveyors
04:14:02.5833 [DEBUG]  Keen:         in file: C:\Games\Space Engineers\PVE Modded\Instance\content\244850\1124114101\Data\BlockVariantGroups.sbc
04:14:02.5833 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: C:\Games\Space Engineers\PVE Modded\Instance\content\244850\1124114101\Textures\GUI\Icons\Cubes\conveyor.dds
04:14:02.5833 [DEBUG]  Keen:       MOD_ERROR: [MAD] More Conveyors
04:14:02.5833 [DEBUG]  Keen:         in file: C:\Games\Space Engineers\PVE Modded\Instance\content\244850\1124114101\Data\BlockVariantGroups.sbc
04:14:02.5833 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: C:\Games\Space Engineers\PVE Modded\Instance\content\244850\1124114101\Textures\GUI\Icons\Cubes\conveyor.dds
04:14:02.5833 [DEBUG]  Keen:       MOD_ERROR: [MAD] More Conveyors
04:14:02.5833 [DEBUG]  Keen:         in file: C:\Games\Space Engineers\PVE Modded\Instance\content\244850\1124114101\Data\BlockVariantGroups.sbc
04:14:02.5833 [DEBUG]  Keen:         Resource not found, setting to null. Resource path: C:\Games\Space Engineers\PVE Modded\Instance\content\244850\1124114101\Textures\GUI\Icons\Cubes\ConveyorTubeSmall.dds
04:14:02.5833 [DEBUG]  Keen:       Loading block variant groups
```

**Comment by mafoo** [comment]
Thank you for the feedback it looks like it might be related to a missing item in the BlockVariant groups for those second messages so I will look over that first
